// <auto-generated />
namespace Console002.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewStuff2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewStuff2));
        
        string IMigrationMetadata.Id
        {
            get { return "201803120044385_NewStuff2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
